# Generated by Django 2.2.1 on 2019-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190517_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librousuario',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
