# Generated by Django 2.2.1 on 2019-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190520_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreria',
            name='maxLibros',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
